
import React from 'react';
import { marked } from 'marked';
import { Plan, Chapter } from '../types';
import { PrinterIcon, DocumentTextIcon, BookOpenIcon } from './icons';

interface ExportModalProps {
    isOpen: boolean;
    onClose: () => void;
    plan: Plan | null;
    chapters: Chapter[];
}

const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, plan, chapters }) => {
    if (!isOpen) return null;

    const title = plan?.worldSettings.summary ? plan.worldSettings.summary.split('.')[0] : 'My Novel';
    const author = 'AI Novelist Agent';

    const handlePrintPDF = () => {
        const printWindow = window.open('', '_blank');
        if (!printWindow) {
            alert('Please allow popups to print the manuscript.');
            return;
        }

        // Render chapters to HTML
        const chaptersHtml = chapters.map(chapter => {
            const htmlContent = marked(chapter.content);
            return `
                <div class="chapter">
                    <h2>${chapter.title}</h2>
                    <div class="chapter-content">${htmlContent}</div>
                </div>
            `;
        }).join('');

        const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>${title}</title>
                <style>
                    @import url('https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700&display=swap');
                    body { 
                        font-family: 'Merriweather', serif; 
                        line-height: 1.8; 
                        max-width: 800px; 
                        margin: 0 auto; 
                        padding: 40px; 
                        color: #1a1a1a; 
                    }
                    h1 { text-align: center; margin-top: 200px; margin-bottom: 50px; font-size: 3em; }
                    .meta { text-align: center; color: #555; margin-bottom: 200px; }
                    .toc { page-break-after: always; margin-top: 100px; }
                    .toc ul { list-style: none; padding: 0; }
                    .toc li { margin-bottom: 10px; border-bottom: 1px dotted #ccc; }
                    .chapter { page-break-before: always; }
                    h2 { margin-top: 50px; margin-bottom: 30px; font-size: 2em; border-bottom: 2px solid #eee; padding-bottom: 10px; }
                    p { margin-bottom: 1.5em; text-align: justify; }
                    
                    @media print {
                        body { max-width: none; padding: 0; }
                        .no-print { display: none; }
                        a { text-decoration: none; color: black; }
                    }
                </style>
            </head>
            <body>
                <h1>${title}</h1>
                <div class="meta">Draft generated by ${author}</div>
                
                <div class="toc">
                    <h3>Table of Contents</h3>
                    <ul>
                        ${chapters.map(c => `<li>${c.title}</li>`).join('')}
                    </ul>
                </div>
                
                ${chaptersHtml}
                
                <script>
                    window.onload = () => { 
                        setTimeout(() => {
                            window.print(); 
                            // window.close(); // Optional: close after print
                        }, 500);
                    }
                </script>
            </body>
            </html>
        `;
        printWindow.document.write(html);
        printWindow.document.close();
    };

    const handleDownloadHTML = () => {
        const chaptersHtml = chapters.map(chapter => {
            return `<section title="${chapter.title}"><h2>${chapter.title}</h2>${marked(chapter.content)}</section>`;
        }).join('\n');

        const fullContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>${title}</title>
    <meta name="author" content="${author}">
    <style>
        body { font-family: serif; line-height: 1.6; }
        section { page-break-before: always; }
    </style>
</head>
<body>
    <h1>${title}</h1>
    ${chaptersHtml}
</body>
</html>`;

        const blob = new Blob([fullContent], { type: 'text/html' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };
    
    const handleDownloadMarkdown = () => {
        const content = chapters.map(c => `# ${c.title}\n\n${c.content}`).join('\n\n---\n\n');
        const blob = new Blob([content], { type: 'text/markdown' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div 
            className="fixed inset-0 bg-black bg-opacity-50 z-50 flex justify-center items-center" 
            onClick={onClose}
        >
            <div 
                className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-md p-6 space-y-6" 
                onClick={(e) => e.stopPropagation()}
            >
                <div className="flex justify-between items-center border-b border-gray-200 dark:border-gray-700 pb-4">
                    <h2 className="text-2xl font-bold text-gray-900 dark:text-white">Export Manuscript</h2>
                    <button onClick={onClose} className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200">
                        <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                <div className="grid grid-cols-1 gap-4">
                    <button 
                        onClick={handlePrintPDF}
                        disabled={chapters.length === 0}
                        className="flex items-center p-4 border rounded-lg hover:bg-gray-50 dark:border-gray-600 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <div className="bg-indigo-100 text-indigo-600 p-3 rounded-full mr-4 dark:bg-indigo-900 dark:text-indigo-300">
                            <PrinterIcon />
                        </div>
                        <div className="text-left">
                            <h3 className="font-bold text-gray-900 dark:text-white">Print to PDF</h3>
                            <p className="text-sm text-gray-500 dark:text-gray-400">Format for print and save as PDF via browser.</p>
                        </div>
                    </button>

                    <button 
                        onClick={handleDownloadHTML}
                        disabled={chapters.length === 0}
                        className="flex items-center p-4 border rounded-lg hover:bg-gray-50 dark:border-gray-600 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <div className="bg-green-100 text-green-600 p-3 rounded-full mr-4 dark:bg-green-900 dark:text-green-300">
                            <BookOpenIcon />
                        </div>
                        <div className="text-left">
                            <h3 className="font-bold text-gray-900 dark:text-white">E-Book (HTML)</h3>
                            <p className="text-sm text-gray-500 dark:text-gray-400">Single file ready for E-Reader conversion.</p>
                        </div>
                    </button>

                    <button 
                        onClick={handleDownloadMarkdown}
                        disabled={chapters.length === 0}
                        className="flex items-center p-4 border rounded-lg hover:bg-gray-50 dark:border-gray-600 dark:hover:bg-gray-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        <div className="bg-gray-100 text-gray-600 p-3 rounded-full mr-4 dark:bg-gray-700 dark:text-gray-300">
                            <DocumentTextIcon />
                        </div>
                        <div className="text-left">
                            <h3 className="font-bold text-gray-900 dark:text-white">Markdown</h3>
                            <p className="text-sm text-gray-500 dark:text-gray-400">Raw text format for editing.</p>
                        </div>
                    </button>
                </div>
            </div>
        </div>
    );
};

export default ExportModal;
